### ISSUE TITLE
Book 3

### ISSUE THREAD

**Issue by doubleshow** [bigdatahci2015/forum#43]
We will begin our third book this week. All the scaffoldings are removed now. You will be working directly with HTML, CSS, and Javascript.

Please create a fork:
https://github.com/bigdatahci2015/book3

We will spend the last portion of today's class to make sure everyone can get the new book running correctly.

**Comment by doubleshow** [comment]
You should be able to see something like this in your browser.

![localhost_8081_week9_](https://cloud.githubusercontent.com/assets/129562/10591233/5f1b1410-7672-11e5-9d42-5fa9569d430a.png)

**Comment by KevinKGifford** [comment]
No SUMMARY file after clone and gitbook serve:

gifford@Kevins-MacBook-Pro-2 /Users/gifford/4830/book3> ll

total 32

-rw-r--r--  1 gifford  staff  1082 Oct 19 15:03 LICENSE

-rw-r--r--  1 gifford  staff    53 Oct 19 15:08 README.md

-rw-r--r--  1 gifford  staff   537 Oct 19 15:03 build.js

-rw-r--r--  1 gifford  staff   357 Oct 19 15:03 package.json

drwxr-xr-x  6 gifford  staff   204 Oct 19 15:03 src

gifford@Kevins-MacBook-Pro-2 /Users/gifford/4830/book3> git remote -v

origin https://github.com/KevinKGifford/book3.git (fetch)

origin https://github.com/KevinKGifford/book3.git (push)

upstream https://github.com/bigdatahci2015/book3.git (fetch)

upstream https://github.com/bigdatahci2015/book3.git (push)

gifford@Kevins-MacBook-Pro-2 /Users/gifford/4830/book3> gitbook serve

Live reload server started on port: 35729

Press CTRL+C to quit ...

info: loading book configuration....OK

info: load plugin gitbook-plugin-highlight ....OK

info: load plugin gitbook-plugin-search ....OK

info: load plugin gitbook-plugin-sharing ....OK

info: load plugin gitbook-plugin-fontsettings ....OK

info: load plugin gitbook-plugin-livereload ....OK

info: >> 5 plugins loaded

No SUMMARY file

gifford@Kevins-MacBook-Pro-2 /Users/gifford/4830/book3>

**Comment by doubleshow** [comment]
try

```
$ node build.js
```

we are no longer using gitbook. please confirm it works.

**Comment by zhya215** [comment]
I got error below:
/Users/zhiliyang/Documents/CUBoulder/CSCI4830-006_BIG_DATA/book3/node_modules/metalsmith/lib/index.js:190
Metalsmith.prototype.build = unyield(function*(){
                                             ^
SyntaxError: Unexpected token *
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/zhiliyang/Documents/CUBoulder/CSCI4830-006_BIG_DATA/book3/node_modules/metalsmith/index.js:6:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

It seems something wrong with '*'

-Zhili

**Comment by KevinKGifford** [comment]
Did an npm update to pull in any new modules, then receive the following
error:

gifford@Kevins-MacBook-Pro-2 /Users/gifford/4830/book3> node build.js

/Users/gifford/4830/book3/node_modules/metalsmith/lib/index.js:190

Metalsmith.prototype.build = unyield(function*(){

```
                                         ^
```

SyntaxError: Unexpected token *

```
at exports.runInThisContext (vm.js:73:16)

at Module._compile (module.js:443:25)

at Object.Module._extensions..js (module.js:478:10)

at Module.load (module.js:355:32)

at Function.Module._load (module.js:310:12)

at Module.require (module.js:365:17)

at require (module.js:384:17)

at Object.<anonymous>
```

(/Users/gifford/4830/book3/node_modules/metalsmith/index.js:6:18)

```
at Module._compile (module.js:460:26)

at Object.Module._extensions..js (module.js:478:10)
```

gifford@Kevins-MacBook-Pro-2 /Users/gifford/4830/book3>

**Comment by doubleshow** [comment]
can you try to update your node.js installation too?

https://nodejs.org/en/
Current Version: v4.2.1

**Comment by doubleshow** [comment]
example of a live book published on gh-pages

http://doubleshow.github.io/book3/

**Comment by zhya215** [comment]
It works now. Thanks

**Comment by KevinKGifford** [comment]
Yep, that does it.  Tks.

**Comment by bdmckean** [comment]
Hi Tom,
Your pokemon page doesn't load the data.  I had the same problem when I tried to upload my pages

Failed to load resource: the server responded with a status of 404 (Not Found)
http://doubleshow.github.io/data/pokemon.small.json 

Brian

**Comment by doubleshow** [comment]
I wonder if it's cross-domain issue. Can you try from a different browser?

**Comment by bdmckean** [comment]
I have the same error using Chrome, Firefox & Safari.
